name = "family-calendar-reminder"
main = "worker/src/index.ts"
compatibility_date = "2026-03-02"
workers_dev = true

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "nl-calendar-reminder-db"
database_id = "483b1e55-109e-470f-af35-75ad69a7cd32"

[vars]
DEFAULT_TIMEZONE = "Asia/Taipei"
FRONTEND_BASE_URL = "http://localhost:8788"
GOOGLE_CALENDAR_ID = "primary"

[triggers]
crons = ["* * * * *"]
